image: docker

stages:
  - lint
  - build
  - deploy
  
lint:
  image: node:10.15-alpine
  stage: lint
  tags: 
    - node
  cache:
    paths:
      - node_modules
  script:
    - npm install --registry=https://npm.gisauto.ru
    - npm run lint

biuld:
  stage: build
  image: node:10.15-alpine
  tags:
    - node
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - public
  script:
    - npm run generate

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
      - public
  only:
  - master



